### ISSUE TITLE
DHT11: eternal timeout

### ISSUE THREAD

**Issue by dvv** [markruys/arduino-DHT#1]
Hello!

Am using example for this library.
Am getting `age == 92` here https://github.com/markruys/arduino-DHT/blob/master/DHT.cpp#L149
Changing condition to be `age > 92` doesn't solve eternal TIMEOUTs.

What can be wrong?

TIA,
--Vladimir

**Comment by lining130965** [comment]
i have the same problerm  ......but it now good....you must first setting      tools/cpu 5V 16M   .
